### ISSUE TITLE
multilanguage similarity

### ISSUE THREAD

**Issue by hanasian** [rrice/java-string-similarity#7]
Hello!
Can the java-string-similarity be applied to many languages such as Germany,French,Chinese and so on.Can it be is relative to language type?

**Comment by rrice** [comment]
It depends on the language, alphabet and the algorithm strategy. The library has a few known strategies included. Each of these strategies implement a different algorithm for analysis. For consistency between strategies, the library requires each strategy to normalize their score values to be between 0.0 and 1.0. To answer your question properly, let me describe the difference between two strategies.

The [JaroStrategy](https://github.com/rrice/java-string-similarity/blob/master/src/main/java/net/ricecode/similarity/JaroStrategy.java) is an edit-distance algorithm. It matches the number of matching characters in each string and the number of transpositions to calculate the edit distance between them. Alternatively, the [DiceCoefficientStrategy](https://github.com/rrice/java-string-similarity/blob/master/src/main/java/net/ricecode/similarity/DiceCoefficientStrategy.java) uses a form of  of [n-gram analysis](https://en.wikipedia.org/wiki/N-gram). In this strategy, splits text into bi-grams (2 character) sets. The coefficient is a ratio between the scaled number of bi-grams found in both strings versus the total number of bi-grams in both strings. 

I believe that most of the strategies can be used in most Latin, Germanic, and Cyrillic languages.  However, the edit-distance algorithms (Jaro, Jaro-Winkler, Levenshtein) would not work well in Asian languages because those algorithms measures distances between letters of a word. The structure of Asian languages are completely different. N-gram algorithms may work better because the N-gram analysis models the probability that a sequence of characters occur or not occur.

**Comment by hanasian** [comment]
Thanks very much rrice!
For your answer,I am very pleased！But for my requirement，I need to calculate the similarity between  two sentences for many languages including Asian languages.Can I use your project directly？Or I need to add the Word segmentation algorithm for different languages.Please give me a few suggestions.
