### ISSUE TITLE
Add the optimized version of dice cofficient? 

### ISSUE THREAD

**Issue by Sasiko** [rrice/java-string-similarity#9]
Could you consider adding another version of Dice algorithm as this one is considered a more accurate and optimized version.

https://en.wikibooks.org/wiki/Algorithm_Implementation/Strings/Dice%27s_coefficient#Java

 * Here's an optimized version of the dice coefficient calculation. It takes
 * advantage of the fact that a bigram of 2 chars can be stored in 1 int, and
 * applies a matching algorithm of O(n*log(n)) instead of O(n*n).
 * 
 * <p>Note that, at the time of writing, this implementation differs from the
 * other implementations on this page. Where the other algorithms incorrectly
 * store the generated bigrams in a set (discarding duplicates), this
 * implementation actually treats multiple occurrences of a bigram as unique.
 * The correctness of this behavior is most easily seen when getting the
 * similarity between "GG" and "GGGGGGGG", which should obviously not be 1.
 * @param s The first string
 * @param t The second String
 * @return The dice coefficient between the two input strings. Returns 0 if one
 *         or both of the strings are {@code null}. Also returns 0 if one or both
 *         of the strings contain less than 2 characters and are not equal.
 * @author Jelle Fresen
 */

**Comment by rrice** [comment]
@Sasiko I am certainly not against optimizing Dice Coefficient.  If I understand your proposal, the optimization is to stuff the bigram into an integer, and use the integer representation for comparisons. 

I have a few concerns about the actual algorithm:

- When we stuff the bigram into an integer field, are there any concerns that that stuffed value could possibly be a negative integer? I do not think it would be an issue, since we are only counting sets. As long as the bigram conversion is deterministic, I see no problem with it.
- As it stands now, I believe the current implementation of all strategies does not handle Unicode surrogate pairs well. It has been largely ignored and sort of handle by the methods provided by Java itself (like `Set<T>.retainAll()`). However, since we are basically serializing code points into integer fields in two character blocks, surrogate pairs can be split between two bigrams. One option, I suppose, would be to stuff the values into a long integer (64-bit) value instead.  Do you have any insight on that?

I cannot guarantee when I can actually implement this. However, I do accept pull requests from other contributors. If you would like to attempt to implement it, please let me know.

**Comment by rrice** [comment]
I am closing this item for now. I am looking to do a new major version of the library to remove some of the bloat and take advantage of some of the newer features of Java.
